[PHP]
date.timezone = UTC
memory_limit = 128M
display_errors = stderr
log_errors = Off
error_reporting = E_ALL
magic_quotes_gpc = Off

[mbstring]
mbstring.language = Japanese
mbstring.internal_encoding = UTF-8
